# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NTdf3ycxWxUx7uZrU06F6Ngp2fydK9lt
"""

import numpy as np
import pandas as pd

df = pd.read_csv("Day 3 Dataset.csv")
print(df.head)

print(df.tail)

print(df.shape)

print(df.columns)

print(df.info)

print(df.isnull().sum())

print(df[["age"]])

df['age'].fillna(df['age'].mean(),inplace=True)

print(df.isnull().sum())

df.dropna(inplace = True)
print(df.isnull().sum())

df['age'].fillna(df['age'].mean(),inplace=True)

print(df[df['age']>30])

print(df[df['sex']=="female"])

print(df.groupby('sex')['survived'].mean())

df_sorted= df.sort_values(by='age',ascending=True)
print(df_sorted)

df["Family_si(ze"]=df["sibsp"]+df["parch"]
print(df.head())

print(df['fare'].max())

df.to_csv("cleaned_dataset.csv")

import seaborn as sns
import matplotlib.pyplot as plt

survival_rate = df["survived"].value_counts(normalize=True)*100
survival_rate.plot(kind="bar")
plt.title("survival percentage")
plt.ylabel("percentage")
plt.show()

#sevival percentage is 60%

sns.barplot(x="sex",y="survived",data=df)
plt.title("survival rate by sex")
plt.show()

#servial rage by gender:more female's are sevived more then men

sns.boxplot(x="pclass",y="fare",data=df)
plt.title("fare distribution by class")
plt.show()

#class 1 people paid more fare

df["family_(size)"]= df["sibsp"]+df["parch"]
sns.barplot(x="family_(size)",y="survived",data=df)
plt.title("survival rate by family size")
plt.show()

#the person who is come eith  4 family size they servived most

sns.histplot(df["age"],color="red")
plt.title("age distubution")
plt.show()

#most of  the people lies between age 30-40

sns.histplot(data=df, x="age", hue="survived", palette=["red", "yellow"],bins=20)
plt.title("age distribution by survival")
plt.show()
#

#red color indicate nor sevived and yellow indicates who are sevived

servival = df["survived"].value_counts()
plt.pie(servival,labels=["survived","not survived"],autopct="%1.1f%%",colors=["blue","green"])
plt.title("survival percentage")
plt.show()

sns.scatterplot(x="age",y="fare",data=df)
plt.title("age vs fare")
plt.show()
#

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

df["embarked"].fillna("S",inplace=True)

df["deck"].fillna("unknown",inplace=True)

df.drop(
    ["class", "who", "adult male", "deck", "embark town", "alive"],
    axis=1,
    inplace=True,
    errors='ignore'
)

df["sex"]=df["sex"].map({"male":0,"female":1})

df["embarked"]=df["embarked"].map({"S":0,"C":1,"Q":2})

df["alone"]=df["alone"].map({True:1,False:0})
df.fillna(0,inplace=True)

x=df.drop("survived",axis=1)
y=df["survived"]

x_train,x_test,y_train,y_test=train_test_split(
    x,y,test_size=0.2,random_state=42
)

model = LogisticRegression(max_iter=1000)
model.fit(x_train, y_train)

y_pred=model.predict(x_test)

print(accuracy_score(y_test,y_pred))

cm=confusion_matrix(y_test,y_pred)
sns.heatmap(cm,annot=True,fmt="d")
plt.title("confusion matrix")
print(cm)